//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaelumGameManagerGUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaelumGameManagerGUI.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string AboutMeText {
            get {
                return ResourceManager.GetString("AboutMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Authors.
        /// </summary>
        public static string AddAuthorsText {
            get {
                return ResourceManager.GetString("AddAuthorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s Description (Creator, Programmer, Writer, etc.).
        /// </summary>
        public static string AuthorsDescriptionTextBox {
            get {
                return ResourceManager.GetString("AuthorsDescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s).
        /// </summary>
        public static string AuthorsText {
            get {
                return ResourceManager.GetString("AuthorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AuthorText {
            get {
                return ResourceManager.GetString("AuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Authors.
        /// </summary>
        public static string AvailableAuthorsText {
            get {
                return ResourceManager.GetString("AvailableAuthorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string BuildText {
            get {
                return ResourceManager.GetString("BuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string CardsText {
            get {
                return ResourceManager.GetString("CardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Author.
        /// </summary>
        public static string CreateAuthorText {
            get {
                return ResourceManager.GetString("CreateAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Card.
        /// </summary>
        public static string CreateCardText {
            get {
                return ResourceManager.GetString("CreateCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateText {
            get {
                return ResourceManager.GetString("CreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        public static string DeckText {
            get {
                return ResourceManager.GetString("DeckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        public static string EditCardText {
            get {
                return ResourceManager.GetString("EditCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string EnabledText {
            get {
                return ResourceManager.GetString("EnabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck build failed..
        /// </summary>
        public static string ErrorDeckBuildFailedMessage {
            get {
                return ResourceManager.GetString("ErrorDeckBuildFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unexpected error! Restart recommended!.
        /// </summary>
        public static string ErrorRecommendRestartMessage {
            get {
                return ResourceManager.GetString("ErrorRecommendRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FoldersText {
            get {
                return ResourceManager.GetString("FoldersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string FolderText {
            get {
                return ResourceManager.GetString("FolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Rebuild.
        /// </summary>
        public static string FullRebuildText {
            get {
                return ResourceManager.GetString("FullRebuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Aemulus.
        /// </summary>
        public static string ImportAemulusText {
            get {
                return ResourceManager.GetString("ImportAemulusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string LauncherText {
            get {
                return ResourceManager.GetString("LauncherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string ModsText {
            get {
                return ResourceManager.GetString("ModsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string ModText {
            get {
                return ResourceManager.GetString("ModText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other(s).
        /// </summary>
        public static string OthersText {
            get {
                return ResourceManager.GetString("OthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherText {
            get {
                return ResourceManager.GetString("OtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayText {
            get {
                return ResourceManager.GetString("PlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsText {
            get {
                return ResourceManager.GetString("ToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File.
        /// </summary>
        public static string WindowImageFileFilter {
            get {
                return ResourceManager.GetString("WindowImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile Image....
        /// </summary>
        public static string WindowSelectAvatarTitle {
            get {
                return ResourceManager.GetString("WindowSelectAvatarTitle", resourceCulture);
            }
        }
    }
}
